<?php
/**
 * ListBotsResponseBotsInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sendbird
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendbird Platform SDK
 *
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sendbird\Model;

use \ArrayAccess;
use \Sendbird\ObjectSerializer;

/**
 * ListBotsResponseBotsInner Class Doc Comment
 *
 * @category Class
 * @package  Sendbird
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ListBotsResponseBotsInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'listBotsResponse_bots_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'ai' => '\Sendbird\Model\ListBotsResponseBotsInnerAi',
        'bot' => '\Sendbird\Model\ListBotsResponseBotsInnerBot',
        'bot_callback_url' => 'string',
        'bot_style' => '\Sendbird\Model\ListBotsResponseBotsInnerBotStyle',
        'channel_invitation_preference' => 'int',
        'created_at' => 'int',
        'enable_mark_as_read' => 'bool',
        'first_messages' => '\Sendbird\Model\ListBotsResponseBotsInnerFirstMessagesInner[]',
        'is_privacy_mode' => 'bool',
        'safeguard' => '\Sendbird\Model\ListBotsResponseBotsInnerSafeguard',
        'show_member' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'ai' => null,
        'bot' => null,
        'bot_callback_url' => null,
        'bot_style' => null,
        'channel_invitation_preference' => null,
        'created_at' => 'int64',
        'enable_mark_as_read' => null,
        'first_messages' => null,
        'is_privacy_mode' => null,
        'safeguard' => null,
        'show_member' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ai' => 'ai',
        'bot' => 'bot',
        'bot_callback_url' => 'bot_callback_url',
        'bot_style' => 'bot_style',
        'channel_invitation_preference' => 'channel_invitation_preference',
        'created_at' => 'created_at',
        'enable_mark_as_read' => 'enable_mark_as_read',
        'first_messages' => 'first_messages',
        'is_privacy_mode' => 'is_privacy_mode',
        'safeguard' => 'safeguard',
        'show_member' => 'show_member'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ai' => 'setAi',
        'bot' => 'setBot',
        'bot_callback_url' => 'setBotCallbackUrl',
        'bot_style' => 'setBotStyle',
        'channel_invitation_preference' => 'setChannelInvitationPreference',
        'created_at' => 'setCreatedAt',
        'enable_mark_as_read' => 'setEnableMarkAsRead',
        'first_messages' => 'setFirstMessages',
        'is_privacy_mode' => 'setIsPrivacyMode',
        'safeguard' => 'setSafeguard',
        'show_member' => 'setShowMember'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ai' => 'getAi',
        'bot' => 'getBot',
        'bot_callback_url' => 'getBotCallbackUrl',
        'bot_style' => 'getBotStyle',
        'channel_invitation_preference' => 'getChannelInvitationPreference',
        'created_at' => 'getCreatedAt',
        'enable_mark_as_read' => 'getEnableMarkAsRead',
        'first_messages' => 'getFirstMessages',
        'is_privacy_mode' => 'getIsPrivacyMode',
        'safeguard' => 'getSafeguard',
        'show_member' => 'getShowMember'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ai'] = $data['ai'] ?? null;
        $this->container['bot'] = $data['bot'] ?? null;
        $this->container['bot_callback_url'] = $data['bot_callback_url'] ?? null;
        $this->container['bot_style'] = $data['bot_style'] ?? null;
        $this->container['channel_invitation_preference'] = $data['channel_invitation_preference'] ?? null;
        $this->container['created_at'] = $data['created_at'] ?? null;
        $this->container['enable_mark_as_read'] = $data['enable_mark_as_read'] ?? null;
        $this->container['first_messages'] = $data['first_messages'] ?? null;
        $this->container['is_privacy_mode'] = $data['is_privacy_mode'] ?? null;
        $this->container['safeguard'] = $data['safeguard'] ?? null;
        $this->container['show_member'] = $data['show_member'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ai
     *
     * @return \Sendbird\Model\ListBotsResponseBotsInnerAi|null
     */
    public function getAi()
    {
        return $this->container['ai'];
    }

    /**
     * Sets ai
     *
     * @param \Sendbird\Model\ListBotsResponseBotsInnerAi|null $ai ai
     *
     * @return self
     */
    public function setAi($ai)
    {
        $this->container['ai'] = $ai;

        return $this;
    }

    /**
     * Gets bot
     *
     * @return \Sendbird\Model\ListBotsResponseBotsInnerBot|null
     */
    public function getBot()
    {
        return $this->container['bot'];
    }

    /**
     * Sets bot
     *
     * @param \Sendbird\Model\ListBotsResponseBotsInnerBot|null $bot bot
     *
     * @return self
     */
    public function setBot($bot)
    {
        $this->container['bot'] = $bot;

        return $this;
    }

    /**
     * Gets bot_callback_url
     *
     * @return string|null
     */
    public function getBotCallbackUrl()
    {
        return $this->container['bot_callback_url'];
    }

    /**
     * Sets bot_callback_url
     *
     * @param string|null $bot_callback_url bot_callback_url
     *
     * @return self
     */
    public function setBotCallbackUrl($bot_callback_url)
    {
        $this->container['bot_callback_url'] = $bot_callback_url;

        return $this;
    }

    /**
     * Gets bot_style
     *
     * @return \Sendbird\Model\ListBotsResponseBotsInnerBotStyle|null
     */
    public function getBotStyle()
    {
        return $this->container['bot_style'];
    }

    /**
     * Sets bot_style
     *
     * @param \Sendbird\Model\ListBotsResponseBotsInnerBotStyle|null $bot_style bot_style
     *
     * @return self
     */
    public function setBotStyle($bot_style)
    {
        $this->container['bot_style'] = $bot_style;

        return $this;
    }

    /**
     * Gets channel_invitation_preference
     *
     * @return int|null
     */
    public function getChannelInvitationPreference()
    {
        return $this->container['channel_invitation_preference'];
    }

    /**
     * Sets channel_invitation_preference
     *
     * @param int|null $channel_invitation_preference channel_invitation_preference
     *
     * @return self
     */
    public function setChannelInvitationPreference($channel_invitation_preference)
    {
        $this->container['channel_invitation_preference'] = $channel_invitation_preference;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return int|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param int|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets enable_mark_as_read
     *
     * @return bool|null
     */
    public function getEnableMarkAsRead()
    {
        return $this->container['enable_mark_as_read'];
    }

    /**
     * Sets enable_mark_as_read
     *
     * @param bool|null $enable_mark_as_read enable_mark_as_read
     *
     * @return self
     */
    public function setEnableMarkAsRead($enable_mark_as_read)
    {
        $this->container['enable_mark_as_read'] = $enable_mark_as_read;

        return $this;
    }

    /**
     * Gets first_messages
     *
     * @return \Sendbird\Model\ListBotsResponseBotsInnerFirstMessagesInner[]|null
     */
    public function getFirstMessages()
    {
        return $this->container['first_messages'];
    }

    /**
     * Sets first_messages
     *
     * @param \Sendbird\Model\ListBotsResponseBotsInnerFirstMessagesInner[]|null $first_messages first_messages
     *
     * @return self
     */
    public function setFirstMessages($first_messages)
    {
        $this->container['first_messages'] = $first_messages;

        return $this;
    }

    /**
     * Gets is_privacy_mode
     *
     * @return bool|null
     */
    public function getIsPrivacyMode()
    {
        return $this->container['is_privacy_mode'];
    }

    /**
     * Sets is_privacy_mode
     *
     * @param bool|null $is_privacy_mode is_privacy_mode
     *
     * @return self
     */
    public function setIsPrivacyMode($is_privacy_mode)
    {
        $this->container['is_privacy_mode'] = $is_privacy_mode;

        return $this;
    }

    /**
     * Gets safeguard
     *
     * @return \Sendbird\Model\ListBotsResponseBotsInnerSafeguard|null
     */
    public function getSafeguard()
    {
        return $this->container['safeguard'];
    }

    /**
     * Sets safeguard
     *
     * @param \Sendbird\Model\ListBotsResponseBotsInnerSafeguard|null $safeguard safeguard
     *
     * @return self
     */
    public function setSafeguard($safeguard)
    {
        $this->container['safeguard'] = $safeguard;

        return $this;
    }

    /**
     * Gets show_member
     *
     * @return bool|null
     */
    public function getShowMember()
    {
        return $this->container['show_member'];
    }

    /**
     * Sets show_member
     *
     * @param bool|null $show_member show_member
     *
     * @return self
     */
    public function setShowMember($show_member)
    {
        $this->container['show_member'] = $show_member;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


