<?php
/**
 * SendBirdOpenChannelListQuery
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendbird Platform SDK
 *
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SendBirdOpenChannelListQuery Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SendBirdOpenChannelListQuery implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SendBird.OpenChannelListQuery';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'custom_types' => 'string[]',
        'has_next' => 'bool',
        'include_frozen' => 'bool',
        'limit' => 'float',
        'name_keyword' => 'string',
        'url_keyword' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'custom_types' => null,
        'has_next' => null,
        'include_frozen' => null,
        'limit' => null,
        'name_keyword' => null,
        'url_keyword' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'custom_types' => 'customTypes',
        'has_next' => 'hasNext',
        'include_frozen' => 'includeFrozen',
        'limit' => 'limit',
        'name_keyword' => 'nameKeyword',
        'url_keyword' => 'urlKeyword'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'custom_types' => 'setCustomTypes',
        'has_next' => 'setHasNext',
        'include_frozen' => 'setIncludeFrozen',
        'limit' => 'setLimit',
        'name_keyword' => 'setNameKeyword',
        'url_keyword' => 'setUrlKeyword'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'custom_types' => 'getCustomTypes',
        'has_next' => 'getHasNext',
        'include_frozen' => 'getIncludeFrozen',
        'limit' => 'getLimit',
        'name_keyword' => 'getNameKeyword',
        'url_keyword' => 'getUrlKeyword'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['custom_types'] = $data['custom_types'] ?? null;
        $this->container['has_next'] = $data['has_next'] ?? null;
        $this->container['include_frozen'] = $data['include_frozen'] ?? null;
        $this->container['limit'] = $data['limit'] ?? null;
        $this->container['name_keyword'] = $data['name_keyword'] ?? null;
        $this->container['url_keyword'] = $data['url_keyword'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets custom_types
     *
     * @return string[]|null
     */
    public function getCustomTypes()
    {
        return $this->container['custom_types'];
    }

    /**
     * Sets custom_types
     *
     * @param string[]|null $custom_types custom_types
     *
     * @return self
     */
    public function setCustomTypes($custom_types)
    {
        $this->container['custom_types'] = $custom_types;

        return $this;
    }

    /**
     * Gets has_next
     *
     * @return bool|null
     */
    public function getHasNext()
    {
        return $this->container['has_next'];
    }

    /**
     * Sets has_next
     *
     * @param bool|null $has_next has_next
     *
     * @return self
     */
    public function setHasNext($has_next)
    {
        $this->container['has_next'] = $has_next;

        return $this;
    }

    /**
     * Gets include_frozen
     *
     * @return bool|null
     */
    public function getIncludeFrozen()
    {
        return $this->container['include_frozen'];
    }

    /**
     * Sets include_frozen
     *
     * @param bool|null $include_frozen include_frozen
     *
     * @return self
     */
    public function setIncludeFrozen($include_frozen)
    {
        $this->container['include_frozen'] = $include_frozen;

        return $this;
    }

    /**
     * Gets limit
     *
     * @return float|null
     */
    public function getLimit()
    {
        return $this->container['limit'];
    }

    /**
     * Sets limit
     *
     * @param float|null $limit limit
     *
     * @return self
     */
    public function setLimit($limit)
    {
        $this->container['limit'] = $limit;

        return $this;
    }

    /**
     * Gets name_keyword
     *
     * @return string|null
     */
    public function getNameKeyword()
    {
        return $this->container['name_keyword'];
    }

    /**
     * Sets name_keyword
     *
     * @param string|null $name_keyword name_keyword
     *
     * @return self
     */
    public function setNameKeyword($name_keyword)
    {
        $this->container['name_keyword'] = $name_keyword;

        return $this;
    }

    /**
     * Gets url_keyword
     *
     * @return string|null
     */
    public function getUrlKeyword()
    {
        return $this->container['url_keyword'];
    }

    /**
     * Sets url_keyword
     *
     * @param string|null $url_keyword url_keyword
     *
     * @return self
     */
    public function setUrlKeyword($url_keyword)
    {
        $this->container['url_keyword'] = $url_keyword;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


