<?php
/**
 * SendBirdMessageChangeLogsParams
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendbird Platform SDK
 *
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SendBirdMessageChangeLogsParams Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SendBirdMessageChangeLogsParams implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SendBird.MessageChangeLogsParams';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'include_meta_array' => 'bool',
        'include_parent_message_info' => 'bool',
        'include_parent_message_text' => 'bool',
        'include_poll_details' => 'bool',
        'include_reaction' => 'bool',
        'include_reactions' => 'bool',
        'include_replies' => 'bool',
        'include_thread_info' => 'bool',
        'reply_type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'include_meta_array' => null,
        'include_parent_message_info' => null,
        'include_parent_message_text' => null,
        'include_poll_details' => null,
        'include_reaction' => null,
        'include_reactions' => null,
        'include_replies' => null,
        'include_thread_info' => null,
        'reply_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'include_meta_array' => 'includeMetaArray',
        'include_parent_message_info' => 'includeParentMessageInfo',
        'include_parent_message_text' => 'includeParentMessageText',
        'include_poll_details' => 'includePollDetails',
        'include_reaction' => 'includeReaction',
        'include_reactions' => 'includeReactions',
        'include_replies' => 'includeReplies',
        'include_thread_info' => 'includeThreadInfo',
        'reply_type' => 'replyType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'include_meta_array' => 'setIncludeMetaArray',
        'include_parent_message_info' => 'setIncludeParentMessageInfo',
        'include_parent_message_text' => 'setIncludeParentMessageText',
        'include_poll_details' => 'setIncludePollDetails',
        'include_reaction' => 'setIncludeReaction',
        'include_reactions' => 'setIncludeReactions',
        'include_replies' => 'setIncludeReplies',
        'include_thread_info' => 'setIncludeThreadInfo',
        'reply_type' => 'setReplyType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'include_meta_array' => 'getIncludeMetaArray',
        'include_parent_message_info' => 'getIncludeParentMessageInfo',
        'include_parent_message_text' => 'getIncludeParentMessageText',
        'include_poll_details' => 'getIncludePollDetails',
        'include_reaction' => 'getIncludeReaction',
        'include_reactions' => 'getIncludeReactions',
        'include_replies' => 'getIncludeReplies',
        'include_thread_info' => 'getIncludeThreadInfo',
        'reply_type' => 'getReplyType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const REPLY_TYPE_ALL = 'all';
    const REPLY_TYPE_NONE = 'none';
    const REPLY_TYPE_ONLY_REPLY_TO_CHANNEL = 'only_reply_to_channel';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getReplyTypeAllowableValues()
    {
        return [
            self::REPLY_TYPE_ALL,
            self::REPLY_TYPE_NONE,
            self::REPLY_TYPE_ONLY_REPLY_TO_CHANNEL,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['include_meta_array'] = $data['include_meta_array'] ?? null;
        $this->container['include_parent_message_info'] = $data['include_parent_message_info'] ?? null;
        $this->container['include_parent_message_text'] = $data['include_parent_message_text'] ?? null;
        $this->container['include_poll_details'] = $data['include_poll_details'] ?? null;
        $this->container['include_reaction'] = $data['include_reaction'] ?? null;
        $this->container['include_reactions'] = $data['include_reactions'] ?? null;
        $this->container['include_replies'] = $data['include_replies'] ?? null;
        $this->container['include_thread_info'] = $data['include_thread_info'] ?? null;
        $this->container['reply_type'] = $data['reply_type'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getReplyTypeAllowableValues();
        if (!is_null($this->container['reply_type']) && !in_array($this->container['reply_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'reply_type', must be one of '%s'",
                $this->container['reply_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets include_meta_array
     *
     * @return bool|null
     */
    public function getIncludeMetaArray()
    {
        return $this->container['include_meta_array'];
    }

    /**
     * Sets include_meta_array
     *
     * @param bool|null $include_meta_array include_meta_array
     *
     * @return self
     */
    public function setIncludeMetaArray($include_meta_array)
    {
        $this->container['include_meta_array'] = $include_meta_array;

        return $this;
    }

    /**
     * Gets include_parent_message_info
     *
     * @return bool|null
     */
    public function getIncludeParentMessageInfo()
    {
        return $this->container['include_parent_message_info'];
    }

    /**
     * Sets include_parent_message_info
     *
     * @param bool|null $include_parent_message_info include_parent_message_info
     *
     * @return self
     */
    public function setIncludeParentMessageInfo($include_parent_message_info)
    {
        $this->container['include_parent_message_info'] = $include_parent_message_info;

        return $this;
    }

    /**
     * Gets include_parent_message_text
     *
     * @return bool|null
     */
    public function getIncludeParentMessageText()
    {
        return $this->container['include_parent_message_text'];
    }

    /**
     * Sets include_parent_message_text
     *
     * @param bool|null $include_parent_message_text include_parent_message_text
     *
     * @return self
     */
    public function setIncludeParentMessageText($include_parent_message_text)
    {
        $this->container['include_parent_message_text'] = $include_parent_message_text;

        return $this;
    }

    /**
     * Gets include_poll_details
     *
     * @return bool|null
     */
    public function getIncludePollDetails()
    {
        return $this->container['include_poll_details'];
    }

    /**
     * Sets include_poll_details
     *
     * @param bool|null $include_poll_details include_poll_details
     *
     * @return self
     */
    public function setIncludePollDetails($include_poll_details)
    {
        $this->container['include_poll_details'] = $include_poll_details;

        return $this;
    }

    /**
     * Gets include_reaction
     *
     * @return bool|null
     */
    public function getIncludeReaction()
    {
        return $this->container['include_reaction'];
    }

    /**
     * Sets include_reaction
     *
     * @param bool|null $include_reaction include_reaction
     *
     * @return self
     */
    public function setIncludeReaction($include_reaction)
    {
        $this->container['include_reaction'] = $include_reaction;

        return $this;
    }

    /**
     * Gets include_reactions
     *
     * @return bool|null
     */
    public function getIncludeReactions()
    {
        return $this->container['include_reactions'];
    }

    /**
     * Sets include_reactions
     *
     * @param bool|null $include_reactions include_reactions
     *
     * @return self
     */
    public function setIncludeReactions($include_reactions)
    {
        $this->container['include_reactions'] = $include_reactions;

        return $this;
    }

    /**
     * Gets include_replies
     *
     * @return bool|null
     */
    public function getIncludeReplies()
    {
        return $this->container['include_replies'];
    }

    /**
     * Sets include_replies
     *
     * @param bool|null $include_replies include_replies
     *
     * @return self
     */
    public function setIncludeReplies($include_replies)
    {
        $this->container['include_replies'] = $include_replies;

        return $this;
    }

    /**
     * Gets include_thread_info
     *
     * @return bool|null
     */
    public function getIncludeThreadInfo()
    {
        return $this->container['include_thread_info'];
    }

    /**
     * Sets include_thread_info
     *
     * @param bool|null $include_thread_info include_thread_info
     *
     * @return self
     */
    public function setIncludeThreadInfo($include_thread_info)
    {
        $this->container['include_thread_info'] = $include_thread_info;

        return $this;
    }

    /**
     * Gets reply_type
     *
     * @return string|null
     */
    public function getReplyType()
    {
        return $this->container['reply_type'];
    }

    /**
     * Sets reply_type
     *
     * @param string|null $reply_type reply_type
     *
     * @return self
     */
    public function setReplyType($reply_type)
    {
        $allowedValues = $this->getReplyTypeAllowableValues();
        if (!is_null($reply_type) && !in_array($reply_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'reply_type', must be one of '%s'",
                    $reply_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['reply_type'] = $reply_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


