<?php
/**
 * SendBirdGroupChannelFilterStatic
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendbird Platform SDK
 *
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SendBirdGroupChannelFilterStatic Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SendBirdGroupChannelFilterStatic implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SendBird.GroupChannelFilterStatic';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'hidden_channel_filter' => '\OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticHiddenChannelFilter',
        'member_state_filter' => '\OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticMemberStateFilter',
        'public_channel_filter' => '\OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticPublicChannelFilter',
        'query_type' => '\OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticQueryType',
        'search_field' => '\OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticSearchField',
        'super_channel_filter' => '\OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticSuperChannelFilter',
        'unread_channel_filter' => '\OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticUnreadChannelFilter'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'hidden_channel_filter' => null,
        'member_state_filter' => null,
        'public_channel_filter' => null,
        'query_type' => null,
        'search_field' => null,
        'super_channel_filter' => null,
        'unread_channel_filter' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'hidden_channel_filter' => 'HiddenChannelFilter',
        'member_state_filter' => 'MemberStateFilter',
        'public_channel_filter' => 'PublicChannelFilter',
        'query_type' => 'QueryType',
        'search_field' => 'SearchField',
        'super_channel_filter' => 'SuperChannelFilter',
        'unread_channel_filter' => 'UnreadChannelFilter'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'hidden_channel_filter' => 'setHiddenChannelFilter',
        'member_state_filter' => 'setMemberStateFilter',
        'public_channel_filter' => 'setPublicChannelFilter',
        'query_type' => 'setQueryType',
        'search_field' => 'setSearchField',
        'super_channel_filter' => 'setSuperChannelFilter',
        'unread_channel_filter' => 'setUnreadChannelFilter'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'hidden_channel_filter' => 'getHiddenChannelFilter',
        'member_state_filter' => 'getMemberStateFilter',
        'public_channel_filter' => 'getPublicChannelFilter',
        'query_type' => 'getQueryType',
        'search_field' => 'getSearchField',
        'super_channel_filter' => 'getSuperChannelFilter',
        'unread_channel_filter' => 'getUnreadChannelFilter'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['hidden_channel_filter'] = $data['hidden_channel_filter'] ?? null;
        $this->container['member_state_filter'] = $data['member_state_filter'] ?? null;
        $this->container['public_channel_filter'] = $data['public_channel_filter'] ?? null;
        $this->container['query_type'] = $data['query_type'] ?? null;
        $this->container['search_field'] = $data['search_field'] ?? null;
        $this->container['super_channel_filter'] = $data['super_channel_filter'] ?? null;
        $this->container['unread_channel_filter'] = $data['unread_channel_filter'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets hidden_channel_filter
     *
     * @return \OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticHiddenChannelFilter|null
     */
    public function getHiddenChannelFilter()
    {
        return $this->container['hidden_channel_filter'];
    }

    /**
     * Sets hidden_channel_filter
     *
     * @param \OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticHiddenChannelFilter|null $hidden_channel_filter hidden_channel_filter
     *
     * @return self
     */
    public function setHiddenChannelFilter($hidden_channel_filter)
    {
        $this->container['hidden_channel_filter'] = $hidden_channel_filter;

        return $this;
    }

    /**
     * Gets member_state_filter
     *
     * @return \OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticMemberStateFilter|null
     */
    public function getMemberStateFilter()
    {
        return $this->container['member_state_filter'];
    }

    /**
     * Sets member_state_filter
     *
     * @param \OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticMemberStateFilter|null $member_state_filter member_state_filter
     *
     * @return self
     */
    public function setMemberStateFilter($member_state_filter)
    {
        $this->container['member_state_filter'] = $member_state_filter;

        return $this;
    }

    /**
     * Gets public_channel_filter
     *
     * @return \OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticPublicChannelFilter|null
     */
    public function getPublicChannelFilter()
    {
        return $this->container['public_channel_filter'];
    }

    /**
     * Sets public_channel_filter
     *
     * @param \OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticPublicChannelFilter|null $public_channel_filter public_channel_filter
     *
     * @return self
     */
    public function setPublicChannelFilter($public_channel_filter)
    {
        $this->container['public_channel_filter'] = $public_channel_filter;

        return $this;
    }

    /**
     * Gets query_type
     *
     * @return \OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticQueryType|null
     */
    public function getQueryType()
    {
        return $this->container['query_type'];
    }

    /**
     * Sets query_type
     *
     * @param \OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticQueryType|null $query_type query_type
     *
     * @return self
     */
    public function setQueryType($query_type)
    {
        $this->container['query_type'] = $query_type;

        return $this;
    }

    /**
     * Gets search_field
     *
     * @return \OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticSearchField|null
     */
    public function getSearchField()
    {
        return $this->container['search_field'];
    }

    /**
     * Sets search_field
     *
     * @param \OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticSearchField|null $search_field search_field
     *
     * @return self
     */
    public function setSearchField($search_field)
    {
        $this->container['search_field'] = $search_field;

        return $this;
    }

    /**
     * Gets super_channel_filter
     *
     * @return \OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticSuperChannelFilter|null
     */
    public function getSuperChannelFilter()
    {
        return $this->container['super_channel_filter'];
    }

    /**
     * Sets super_channel_filter
     *
     * @param \OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticSuperChannelFilter|null $super_channel_filter super_channel_filter
     *
     * @return self
     */
    public function setSuperChannelFilter($super_channel_filter)
    {
        $this->container['super_channel_filter'] = $super_channel_filter;

        return $this;
    }

    /**
     * Gets unread_channel_filter
     *
     * @return \OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticUnreadChannelFilter|null
     */
    public function getUnreadChannelFilter()
    {
        return $this->container['unread_channel_filter'];
    }

    /**
     * Sets unread_channel_filter
     *
     * @param \OpenAPI\Client\Model\SendBirdGroupChannelFilterStaticUnreadChannelFilter|null $unread_channel_filter unread_channel_filter
     *
     * @return self
     */
    public function setUnreadChannelFilter($unread_channel_filter)
    {
        $this->container['unread_channel_filter'] = $unread_channel_filter;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


