<?php
/**
 * SendBirdPublicGroupChannelListQuery
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendbird Platform SDK
 *
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SendBirdPublicGroupChannelListQuery Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SendBirdPublicGroupChannelListQuery implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SendBird.PublicGroupChannelListQuery';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'channel_name_contains_filter' => 'string',
        'channel_urls_filter' => 'string[]',
        'custom_type_starts_with_filter' => 'string',
        'custom_types_filter' => 'string[]',
        'has_next' => 'bool',
        'include_empty' => 'bool',
        'include_frozen' => 'bool',
        'is_loading' => 'bool',
        'limit' => 'float',
        'membership_filter' => 'string',
        'metadata_key' => 'string',
        'metadata_order_key_filter' => 'string',
        'metadata_value_starts_with' => 'string',
        'metadata_values' => 'string[]',
        'order' => 'string',
        'super_channel_filter' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'channel_name_contains_filter' => null,
        'channel_urls_filter' => null,
        'custom_type_starts_with_filter' => null,
        'custom_types_filter' => null,
        'has_next' => null,
        'include_empty' => null,
        'include_frozen' => null,
        'is_loading' => null,
        'limit' => null,
        'membership_filter' => null,
        'metadata_key' => null,
        'metadata_order_key_filter' => null,
        'metadata_value_starts_with' => null,
        'metadata_values' => null,
        'order' => null,
        'super_channel_filter' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'channel_name_contains_filter' => 'channelNameContainsFilter',
        'channel_urls_filter' => 'channelUrlsFilter',
        'custom_type_starts_with_filter' => 'customTypeStartsWithFilter',
        'custom_types_filter' => 'customTypesFilter',
        'has_next' => 'hasNext',
        'include_empty' => 'includeEmpty',
        'include_frozen' => 'includeFrozen',
        'is_loading' => 'isLoading',
        'limit' => 'limit',
        'membership_filter' => 'membershipFilter',
        'metadata_key' => 'metadataKey',
        'metadata_order_key_filter' => 'metadataOrderKeyFilter',
        'metadata_value_starts_with' => 'metadataValueStartsWith',
        'metadata_values' => 'metadataValues',
        'order' => 'order',
        'super_channel_filter' => 'superChannelFilter'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'channel_name_contains_filter' => 'setChannelNameContainsFilter',
        'channel_urls_filter' => 'setChannelUrlsFilter',
        'custom_type_starts_with_filter' => 'setCustomTypeStartsWithFilter',
        'custom_types_filter' => 'setCustomTypesFilter',
        'has_next' => 'setHasNext',
        'include_empty' => 'setIncludeEmpty',
        'include_frozen' => 'setIncludeFrozen',
        'is_loading' => 'setIsLoading',
        'limit' => 'setLimit',
        'membership_filter' => 'setMembershipFilter',
        'metadata_key' => 'setMetadataKey',
        'metadata_order_key_filter' => 'setMetadataOrderKeyFilter',
        'metadata_value_starts_with' => 'setMetadataValueStartsWith',
        'metadata_values' => 'setMetadataValues',
        'order' => 'setOrder',
        'super_channel_filter' => 'setSuperChannelFilter'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'channel_name_contains_filter' => 'getChannelNameContainsFilter',
        'channel_urls_filter' => 'getChannelUrlsFilter',
        'custom_type_starts_with_filter' => 'getCustomTypeStartsWithFilter',
        'custom_types_filter' => 'getCustomTypesFilter',
        'has_next' => 'getHasNext',
        'include_empty' => 'getIncludeEmpty',
        'include_frozen' => 'getIncludeFrozen',
        'is_loading' => 'getIsLoading',
        'limit' => 'getLimit',
        'membership_filter' => 'getMembershipFilter',
        'metadata_key' => 'getMetadataKey',
        'metadata_order_key_filter' => 'getMetadataOrderKeyFilter',
        'metadata_value_starts_with' => 'getMetadataValueStartsWith',
        'metadata_values' => 'getMetadataValues',
        'order' => 'getOrder',
        'super_channel_filter' => 'getSuperChannelFilter'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const MEMBERSHIP_FILTER_ALL = 'all';
    const MEMBERSHIP_FILTER_JOINED = 'joined';
    const ORDER_CHANNEL_NAME_ALPHABETICAL = 'channel_name_alphabetical';
    const ORDER_CHRONOLOGICAL = 'chronological';
    const ORDER_METADATA_VALUE_ALPHABETICAL = 'metadata_value_alphabetical';
    const SUPER_CHANNEL_FILTER_ALL = 'all';
    const SUPER_CHANNEL_FILTER_BROADCAST_ONLY = 'broadcast_only';
    const SUPER_CHANNEL_FILTER_NONSUPER = 'nonsuper';
    const SUPER_CHANNEL_FILTER_SUPER = 'super';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMembershipFilterAllowableValues()
    {
        return [
            self::MEMBERSHIP_FILTER_ALL,
            self::MEMBERSHIP_FILTER_JOINED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOrderAllowableValues()
    {
        return [
            self::ORDER_CHANNEL_NAME_ALPHABETICAL,
            self::ORDER_CHRONOLOGICAL,
            self::ORDER_METADATA_VALUE_ALPHABETICAL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSuperChannelFilterAllowableValues()
    {
        return [
            self::SUPER_CHANNEL_FILTER_ALL,
            self::SUPER_CHANNEL_FILTER_BROADCAST_ONLY,
            self::SUPER_CHANNEL_FILTER_NONSUPER,
            self::SUPER_CHANNEL_FILTER_SUPER,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['channel_name_contains_filter'] = $data['channel_name_contains_filter'] ?? null;
        $this->container['channel_urls_filter'] = $data['channel_urls_filter'] ?? null;
        $this->container['custom_type_starts_with_filter'] = $data['custom_type_starts_with_filter'] ?? null;
        $this->container['custom_types_filter'] = $data['custom_types_filter'] ?? null;
        $this->container['has_next'] = $data['has_next'] ?? null;
        $this->container['include_empty'] = $data['include_empty'] ?? null;
        $this->container['include_frozen'] = $data['include_frozen'] ?? null;
        $this->container['is_loading'] = $data['is_loading'] ?? null;
        $this->container['limit'] = $data['limit'] ?? null;
        $this->container['membership_filter'] = $data['membership_filter'] ?? null;
        $this->container['metadata_key'] = $data['metadata_key'] ?? null;
        $this->container['metadata_order_key_filter'] = $data['metadata_order_key_filter'] ?? null;
        $this->container['metadata_value_starts_with'] = $data['metadata_value_starts_with'] ?? null;
        $this->container['metadata_values'] = $data['metadata_values'] ?? null;
        $this->container['order'] = $data['order'] ?? null;
        $this->container['super_channel_filter'] = $data['super_channel_filter'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getMembershipFilterAllowableValues();
        if (!is_null($this->container['membership_filter']) && !in_array($this->container['membership_filter'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'membership_filter', must be one of '%s'",
                $this->container['membership_filter'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getOrderAllowableValues();
        if (!is_null($this->container['order']) && !in_array($this->container['order'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'order', must be one of '%s'",
                $this->container['order'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSuperChannelFilterAllowableValues();
        if (!is_null($this->container['super_channel_filter']) && !in_array($this->container['super_channel_filter'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'super_channel_filter', must be one of '%s'",
                $this->container['super_channel_filter'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets channel_name_contains_filter
     *
     * @return string|null
     */
    public function getChannelNameContainsFilter()
    {
        return $this->container['channel_name_contains_filter'];
    }

    /**
     * Sets channel_name_contains_filter
     *
     * @param string|null $channel_name_contains_filter channel_name_contains_filter
     *
     * @return self
     */
    public function setChannelNameContainsFilter($channel_name_contains_filter)
    {
        $this->container['channel_name_contains_filter'] = $channel_name_contains_filter;

        return $this;
    }

    /**
     * Gets channel_urls_filter
     *
     * @return string[]|null
     */
    public function getChannelUrlsFilter()
    {
        return $this->container['channel_urls_filter'];
    }

    /**
     * Sets channel_urls_filter
     *
     * @param string[]|null $channel_urls_filter channel_urls_filter
     *
     * @return self
     */
    public function setChannelUrlsFilter($channel_urls_filter)
    {
        $this->container['channel_urls_filter'] = $channel_urls_filter;

        return $this;
    }

    /**
     * Gets custom_type_starts_with_filter
     *
     * @return string|null
     */
    public function getCustomTypeStartsWithFilter()
    {
        return $this->container['custom_type_starts_with_filter'];
    }

    /**
     * Sets custom_type_starts_with_filter
     *
     * @param string|null $custom_type_starts_with_filter custom_type_starts_with_filter
     *
     * @return self
     */
    public function setCustomTypeStartsWithFilter($custom_type_starts_with_filter)
    {
        $this->container['custom_type_starts_with_filter'] = $custom_type_starts_with_filter;

        return $this;
    }

    /**
     * Gets custom_types_filter
     *
     * @return string[]|null
     */
    public function getCustomTypesFilter()
    {
        return $this->container['custom_types_filter'];
    }

    /**
     * Sets custom_types_filter
     *
     * @param string[]|null $custom_types_filter custom_types_filter
     *
     * @return self
     */
    public function setCustomTypesFilter($custom_types_filter)
    {
        $this->container['custom_types_filter'] = $custom_types_filter;

        return $this;
    }

    /**
     * Gets has_next
     *
     * @return bool|null
     */
    public function getHasNext()
    {
        return $this->container['has_next'];
    }

    /**
     * Sets has_next
     *
     * @param bool|null $has_next has_next
     *
     * @return self
     */
    public function setHasNext($has_next)
    {
        $this->container['has_next'] = $has_next;

        return $this;
    }

    /**
     * Gets include_empty
     *
     * @return bool|null
     */
    public function getIncludeEmpty()
    {
        return $this->container['include_empty'];
    }

    /**
     * Sets include_empty
     *
     * @param bool|null $include_empty include_empty
     *
     * @return self
     */
    public function setIncludeEmpty($include_empty)
    {
        $this->container['include_empty'] = $include_empty;

        return $this;
    }

    /**
     * Gets include_frozen
     *
     * @return bool|null
     */
    public function getIncludeFrozen()
    {
        return $this->container['include_frozen'];
    }

    /**
     * Sets include_frozen
     *
     * @param bool|null $include_frozen include_frozen
     *
     * @return self
     */
    public function setIncludeFrozen($include_frozen)
    {
        $this->container['include_frozen'] = $include_frozen;

        return $this;
    }

    /**
     * Gets is_loading
     *
     * @return bool|null
     */
    public function getIsLoading()
    {
        return $this->container['is_loading'];
    }

    /**
     * Sets is_loading
     *
     * @param bool|null $is_loading is_loading
     *
     * @return self
     */
    public function setIsLoading($is_loading)
    {
        $this->container['is_loading'] = $is_loading;

        return $this;
    }

    /**
     * Gets limit
     *
     * @return float|null
     */
    public function getLimit()
    {
        return $this->container['limit'];
    }

    /**
     * Sets limit
     *
     * @param float|null $limit limit
     *
     * @return self
     */
    public function setLimit($limit)
    {
        $this->container['limit'] = $limit;

        return $this;
    }

    /**
     * Gets membership_filter
     *
     * @return string|null
     */
    public function getMembershipFilter()
    {
        return $this->container['membership_filter'];
    }

    /**
     * Sets membership_filter
     *
     * @param string|null $membership_filter membership_filter
     *
     * @return self
     */
    public function setMembershipFilter($membership_filter)
    {
        $allowedValues = $this->getMembershipFilterAllowableValues();
        if (!is_null($membership_filter) && !in_array($membership_filter, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'membership_filter', must be one of '%s'",
                    $membership_filter,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['membership_filter'] = $membership_filter;

        return $this;
    }

    /**
     * Gets metadata_key
     *
     * @return string|null
     */
    public function getMetadataKey()
    {
        return $this->container['metadata_key'];
    }

    /**
     * Sets metadata_key
     *
     * @param string|null $metadata_key metadata_key
     *
     * @return self
     */
    public function setMetadataKey($metadata_key)
    {
        $this->container['metadata_key'] = $metadata_key;

        return $this;
    }

    /**
     * Gets metadata_order_key_filter
     *
     * @return string|null
     */
    public function getMetadataOrderKeyFilter()
    {
        return $this->container['metadata_order_key_filter'];
    }

    /**
     * Sets metadata_order_key_filter
     *
     * @param string|null $metadata_order_key_filter metadata_order_key_filter
     *
     * @return self
     */
    public function setMetadataOrderKeyFilter($metadata_order_key_filter)
    {
        $this->container['metadata_order_key_filter'] = $metadata_order_key_filter;

        return $this;
    }

    /**
     * Gets metadata_value_starts_with
     *
     * @return string|null
     */
    public function getMetadataValueStartsWith()
    {
        return $this->container['metadata_value_starts_with'];
    }

    /**
     * Sets metadata_value_starts_with
     *
     * @param string|null $metadata_value_starts_with metadata_value_starts_with
     *
     * @return self
     */
    public function setMetadataValueStartsWith($metadata_value_starts_with)
    {
        $this->container['metadata_value_starts_with'] = $metadata_value_starts_with;

        return $this;
    }

    /**
     * Gets metadata_values
     *
     * @return string[]|null
     */
    public function getMetadataValues()
    {
        return $this->container['metadata_values'];
    }

    /**
     * Sets metadata_values
     *
     * @param string[]|null $metadata_values metadata_values
     *
     * @return self
     */
    public function setMetadataValues($metadata_values)
    {
        $this->container['metadata_values'] = $metadata_values;

        return $this;
    }

    /**
     * Gets order
     *
     * @return string|null
     */
    public function getOrder()
    {
        return $this->container['order'];
    }

    /**
     * Sets order
     *
     * @param string|null $order order
     *
     * @return self
     */
    public function setOrder($order)
    {
        $allowedValues = $this->getOrderAllowableValues();
        if (!is_null($order) && !in_array($order, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'order', must be one of '%s'",
                    $order,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['order'] = $order;

        return $this;
    }

    /**
     * Gets super_channel_filter
     *
     * @return string|null
     */
    public function getSuperChannelFilter()
    {
        return $this->container['super_channel_filter'];
    }

    /**
     * Sets super_channel_filter
     *
     * @param string|null $super_channel_filter super_channel_filter
     *
     * @return self
     */
    public function setSuperChannelFilter($super_channel_filter)
    {
        $allowedValues = $this->getSuperChannelFilterAllowableValues();
        if (!is_null($super_channel_filter) && !in_array($super_channel_filter, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'super_channel_filter', must be one of '%s'",
                    $super_channel_filter,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['super_channel_filter'] = $super_channel_filter;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


