<?php
/**
 * UpdateAUserRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Sendbird
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendbird Platform SDK
 *
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sendbird\Model;

use \ArrayAccess;
use \Sendbird\ObjectSerializer;

/**
 * UpdateAUserRequest Class Doc Comment
 *
 * @category Class
 * @package  Sendbird
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class UpdateAUserRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'updateAUser_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'discovery_keys' => 'string[]',
        'is_active' => 'bool',
        'issue_access_token' => 'bool',
        'last_seen_at' => 'int',
        'leave_all_when_deactivated' => 'bool',
        'nickname' => 'string',
        'preferred_languages' => 'string[]',
        'profile_file' => '\SplFileObject',
        'profile_url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'discovery_keys' => null,
        'is_active' => null,
        'issue_access_token' => null,
        'last_seen_at' => 'int64',
        'leave_all_when_deactivated' => null,
        'nickname' => null,
        'preferred_languages' => null,
        'profile_file' => 'binary',
        'profile_url' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'discovery_keys' => 'discovery_keys',
        'is_active' => 'is_active',
        'issue_access_token' => 'issue_access_token',
        'last_seen_at' => 'last_seen_at',
        'leave_all_when_deactivated' => 'leave_all_when_deactivated',
        'nickname' => 'nickname',
        'preferred_languages' => 'preferred_languages',
        'profile_file' => 'profile_file',
        'profile_url' => 'profile_url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'discovery_keys' => 'setDiscoveryKeys',
        'is_active' => 'setIsActive',
        'issue_access_token' => 'setIssueAccessToken',
        'last_seen_at' => 'setLastSeenAt',
        'leave_all_when_deactivated' => 'setLeaveAllWhenDeactivated',
        'nickname' => 'setNickname',
        'preferred_languages' => 'setPreferredLanguages',
        'profile_file' => 'setProfileFile',
        'profile_url' => 'setProfileUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'discovery_keys' => 'getDiscoveryKeys',
        'is_active' => 'getIsActive',
        'issue_access_token' => 'getIssueAccessToken',
        'last_seen_at' => 'getLastSeenAt',
        'leave_all_when_deactivated' => 'getLeaveAllWhenDeactivated',
        'nickname' => 'getNickname',
        'preferred_languages' => 'getPreferredLanguages',
        'profile_file' => 'getProfileFile',
        'profile_url' => 'getProfileUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['discovery_keys'] = $data['discovery_keys'] ?? null;
        $this->container['is_active'] = $data['is_active'] ?? null;
        $this->container['issue_access_token'] = $data['issue_access_token'] ?? null;
        $this->container['last_seen_at'] = $data['last_seen_at'] ?? null;
        $this->container['leave_all_when_deactivated'] = $data['leave_all_when_deactivated'] ?? null;
        $this->container['nickname'] = $data['nickname'] ?? null;
        $this->container['preferred_languages'] = $data['preferred_languages'] ?? null;
        $this->container['profile_file'] = $data['profile_file'] ?? null;
        $this->container['profile_url'] = $data['profile_url'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets discovery_keys
     *
     * @return string[]|null
     */
    public function getDiscoveryKeys()
    {
        return $this->container['discovery_keys'];
    }

    /**
     * Sets discovery_keys
     *
     * @param string[]|null $discovery_keys discovery_keys
     *
     * @return self
     */
    public function setDiscoveryKeys($discovery_keys)
    {
        $this->container['discovery_keys'] = $discovery_keys;

        return $this;
    }

    /**
     * Gets is_active
     *
     * @return bool|null
     */
    public function getIsActive()
    {
        return $this->container['is_active'];
    }

    /**
     * Sets is_active
     *
     * @param bool|null $is_active is_active
     *
     * @return self
     */
    public function setIsActive($is_active)
    {
        $this->container['is_active'] = $is_active;

        return $this;
    }

    /**
     * Gets issue_access_token
     *
     * @return bool|null
     */
    public function getIssueAccessToken()
    {
        return $this->container['issue_access_token'];
    }

    /**
     * Sets issue_access_token
     *
     * @param bool|null $issue_access_token issue_access_token
     *
     * @return self
     */
    public function setIssueAccessToken($issue_access_token)
    {
        $this->container['issue_access_token'] = $issue_access_token;

        return $this;
    }

    /**
     * Gets last_seen_at
     *
     * @return int|null
     */
    public function getLastSeenAt()
    {
        return $this->container['last_seen_at'];
    }

    /**
     * Sets last_seen_at
     *
     * @param int|null $last_seen_at last_seen_at
     *
     * @return self
     */
    public function setLastSeenAt($last_seen_at)
    {
        $this->container['last_seen_at'] = $last_seen_at;

        return $this;
    }

    /**
     * Gets leave_all_when_deactivated
     *
     * @return bool|null
     */
    public function getLeaveAllWhenDeactivated()
    {
        return $this->container['leave_all_when_deactivated'];
    }

    /**
     * Sets leave_all_when_deactivated
     *
     * @param bool|null $leave_all_when_deactivated leave_all_when_deactivated
     *
     * @return self
     */
    public function setLeaveAllWhenDeactivated($leave_all_when_deactivated)
    {
        $this->container['leave_all_when_deactivated'] = $leave_all_when_deactivated;

        return $this;
    }

    /**
     * Gets nickname
     *
     * @return string|null
     */
    public function getNickname()
    {
        return $this->container['nickname'];
    }

    /**
     * Sets nickname
     *
     * @param string|null $nickname nickname
     *
     * @return self
     */
    public function setNickname($nickname)
    {
        $this->container['nickname'] = $nickname;

        return $this;
    }

    /**
     * Gets preferred_languages
     *
     * @return string[]|null
     */
    public function getPreferredLanguages()
    {
        return $this->container['preferred_languages'];
    }

    /**
     * Sets preferred_languages
     *
     * @param string[]|null $preferred_languages preferred_languages
     *
     * @return self
     */
    public function setPreferredLanguages($preferred_languages)
    {
        $this->container['preferred_languages'] = $preferred_languages;

        return $this;
    }

    /**
     * Gets profile_file
     *
     * @return \SplFileObject|null
     */
    public function getProfileFile()
    {
        return $this->container['profile_file'];
    }

    /**
     * Sets profile_file
     *
     * @param \SplFileObject|null $profile_file profile_file
     *
     * @return self
     */
    public function setProfileFile($profile_file)
    {
        $this->container['profile_file'] = $profile_file;

        return $this;
    }

    /**
     * Gets profile_url
     *
     * @return string|null
     */
    public function getProfileUrl()
    {
        return $this->container['profile_url'];
    }

    /**
     * Sets profile_url
     *
     * @param string|null $profile_url profile_url
     *
     * @return self
     */
    public function setProfileUrl($profile_url)
    {
        $this->container['profile_url'] = $profile_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


